apiVersion: v1
kind: Pod
metadata:
  labels:
    pod: hpc
  name: hpc
spec:
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: "NT AUTHORITY\\SYSTEM"
  hostNetwork: true
  containers:
    - name: hpc
      image: wcctcontainerregistry.azurecr.io/monagent:v1
      imagePullPolicy: IfNotPresent
      command: ["cmd", "/C"]
      args:  ["ping", "-t", "localhost"]
  nodeSelector:
    "kubernetes.io/os": windows
